# -*- coding: utf-8 -*-
"""
GI/GL 食物卡牌分类游戏 —— 卡牌数据库
数据来源：《游戏脚本1---GI和GL卡牌游戏.docx》
每张卡牌为 dict，字段：
  name     食物名称
  category 品类（水果/蔬菜/主食/蛋白/零食/坚果/饮品）
  gi       GI 数值（字符串，可为范围）
  gl       GL 数值（字符串，可为范围）
  gi_level GI 等级：低GI / 中GI / 高GI
  gl_level GL 等级：低GL / 中GL / 高GL
  tip      控糖提示
"""

# ============================================================
# 关卡1：水果卡牌库（30 种）
# ============================================================
FRUITS = [
    # ---- 低GI 水果 ----
    {"name": "小番茄", "category": "水果", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，升糖平缓，糖友可放心适量食用。"},
    {"name": "草莓", "category": "水果", "gi": "27", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI低GL，甜但负担小，是糖友优选水果。"},
    {"name": "李子", "category": "水果", "gi": "24", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，升糖平缓。"},
    {"name": "西梅", "category": "水果", "gi": "24", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，升糖平缓。"},
    {"name": "柚子", "category": "水果", "gi": "24", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，果肉升糖平缓。"},
    {"name": "樱桃", "category": "水果", "gi": "22", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI低GL，甜而不负担，可适量吃。"},
    {"name": "桃子", "category": "水果", "gi": "28", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，升糖平缓。"},
    {"name": "番石榴", "category": "水果", "gi": "31", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，纤维丰富。"},
    {"name": "木瓜", "category": "水果", "gi": "30", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，升糖平缓。"},
    {"name": "梨子", "category": "水果", "gi": "36", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，升糖平缓。"},
    {"name": "橘子", "category": "水果", "gi": "43", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，整颗吃比榨汁负担更小。"},
    {"name": "苹果", "category": "水果", "gi": "36", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，带皮吃增加膳食纤维。"},
    {"name": "橙子", "category": "水果", "gi": "43", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，整颗吃优于榨汁。"},
    {"name": "蓝莓", "category": "水果", "gi": "34", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI低GL，抗氧化，可适量吃。"},
    {"name": "火龙果", "category": "水果", "gi": "38", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，升糖平缓。"},
    {"name": "柿子", "category": "水果", "gi": "50", "gl": "7", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，但含糖不低，注意控量。"},
    {"name": "冬枣", "category": "水果", "gi": "42", "gl": "11", "gi_level": "低GI", "gl_level": "中GL",
     "tip": "陷阱！GI虽低，但GL中等，别当零食大量吃。"},
    {"name": "牛油果", "category": "水果", "gi": "27", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI低GL，富含健康脂肪。"},
    {"name": "榴莲", "category": "水果", "gi": "53", "gl": "15", "gi_level": "低GI", "gl_level": "中GL",
     "tip": "陷阱！GI不算高，但碳水密度大、GL高，严格控量。"},
    {"name": "椰子", "category": "水果", "gi": "40", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI，椰肉含脂肪，适量食用。"},
    {"name": "猕猴桃", "category": "水果", "gi": "52", "gl": "6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI水果，富含维C，升糖平缓。"},
    # ---- 中GI 水果 ----
    {"name": "杏子", "category": "水果", "gi": "57", "gl": "5", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "中GI水果，控制分量食用。"},
    {"name": "芒果", "category": "水果", "gi": "55", "gl": "10", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "中GI中GL，控制分量食用。"},
    {"name": "小葡萄", "category": "水果", "gi": "56", "gl": "11", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "中GI，葡萄含糖集中，控制分量。"},
    {"name": "石榴", "category": "水果", "gi": "67", "gl": "9.4", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "中GI水果，控制分量食用。"},
    {"name": "菠萝", "category": "水果", "gi": "66", "gl": "7", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "中GI水果，控制分量食用。"},
    # ---- 高GI 水果 ----
    {"name": "西瓜", "category": "水果", "gi": "72", "gl": "4", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "陷阱！GI高升糖快，但水分多、GL极低，少量吃负担小。"},
    {"name": "哈密瓜", "category": "水果", "gi": "70", "gl": "6", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "升糖偏快，控制分量，少量食用。"},
    {"name": "荔枝", "category": "水果", "gi": "70", "gl": "11", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "陷阱！升糖快且GL不低，务必控制数量。"},
    {"name": "菠萝蜜", "category": "水果", "gi": "75", "gl": "19", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "高GI且GL偏高，严格控量。"},
]

# ============================================================
# 关卡2：蔬菜卡牌库（25 种）
# ============================================================
VEGETABLES = [
    # ---- 低GI 蔬菜 ----
    {"name": "菠菜", "category": "蔬菜", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "绿叶蔬菜，低GI，可放心多吃。"},
    {"name": "生菜", "category": "蔬菜", "gi": "15", "gl": "0.3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "绿叶蔬菜，低GI低GL，可放心多吃。"},
    {"name": "油菜", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "绿叶蔬菜，低GI，可放心多吃。"},
    {"name": "茼蒿", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "绿叶蔬菜，低GI，可放心多吃。"},
    {"name": "羽衣甘蓝", "category": "蔬菜", "gi": "15", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "绿叶蔬菜，低GI，可放心多吃。"},
    {"name": "黄瓜", "category": "蔬菜", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI低GL，可放心吃。"},
    {"name": "冬瓜", "category": "蔬菜", "gi": "24", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI蔬菜，可放心多吃。"},
    {"name": "番茄", "category": "蔬菜", "gi": "15", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI蔬菜，可放心多吃。"},
    {"name": "西葫芦", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI蔬菜，可放心多吃。"},
    {"name": "香菇", "category": "蔬菜", "gi": "10", "gl": "0.3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "菌菇类低GI，可放心吃。"},
    {"name": "金针菇", "category": "蔬菜", "gi": "19", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "菌菇类低GI，可放心吃。"},
    {"name": "海带", "category": "蔬菜", "gi": "17", "gl": "0.3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI，富含膳食纤维。"},
    {"name": "木耳", "category": "蔬菜", "gi": "26", "gl": "1.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "菌菇类低GI，可放心吃。"},
    {"name": "西蓝花", "category": "蔬菜", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI蔬菜，营养丰富，可放心吃。"},
    {"name": "芦笋", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI蔬菜，可放心吃。"},
    {"name": "秋葵", "category": "蔬菜", "gi": "20", "gl": "1.0", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI蔬菜，富含膳食纤维。"},
    {"name": "茄子", "category": "蔬菜", "gi": "15", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI蔬菜，少油烹调更健康。"},
    {"name": "鹰嘴豆", "category": "蔬菜", "gi": "28", "gl": "5.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI豆类，可替代部分主食。"},
    {"name": "豌豆", "category": "蔬菜", "gi": "54", "gl": "6.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI豆类，含碳水，适量食用。"},
    # ---- 中GI 蔬菜 ----
    {"name": "甜菜根", "category": "蔬菜", "gi": "64", "gl": "5", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "中GI蔬菜，控制分量食用。"},
    {"name": "胡萝卜", "category": "蔬菜", "gi": "71", "gl": "4", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "升糖偏快，控制分量，别当主食大量吃。"},
    # ---- 高GI 蔬菜（淀粉根茎类，本质是主食） ----
    {"name": "土豆", "category": "蔬菜", "gi": "78~90", "gl": "15", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "陷阱！淀粉类高GI食物，当主食替代米饭，别当普通蔬菜大量吃；整块蒸煮，土豆泥GI更高。"},
    {"name": "红薯", "category": "蔬菜", "gi": "70", "gl": "13", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "陷阱！淀粉根茎类，GI偏高，吃它要减主食。"},
    {"name": "山药", "category": "蔬菜", "gi": "75", "gl": "9", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "陷阱！淀粉根茎类，GI偏高，吃它要减主食。"},
    {"name": "南瓜", "category": "蔬菜", "gi": "75", "gl": "6", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "陷阱！淀粉类蔬菜，GI偏高，吃它要减主食。"},
]

# ============================================================
# 关卡3：主食卡牌库（8 种）
# ============================================================
STAPLES = [
    {"name": "黑米", "category": "主食", "gi": "42~50", "gl": "11", "gi_level": "低GI", "gl_level": "中GL",
     "tip": "低GI杂粮，可替换部分白米饭。"},
    {"name": "藜麦", "category": "主食", "gi": "35~53", "gl": "9", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "优质低GI主食，可替换白米饭。"},
    {"name": "燕麦米", "category": "主食", "gi": "50~55", "gl": "9", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GI主食，选原粒燕麦，避开即食加糖麦片。"},
    {"name": "普通糙米", "category": "主食", "gi": "55~68", "gl": "10", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "中GI主食，优于精白米，控制总量。"},
    {"name": "红米", "category": "主食", "gi": "55~65", "gl": "14", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "中GI主食，控制总量。"},
    {"name": "糯米", "category": "主食", "gi": "85~95", "gl": "28", "gi_level": "高GI", "gl_level": "高GL",
     "tip": "陷阱！高GI+高GL，升糖极快，严格少吃。"},
    {"name": "短粒粳米", "category": "主食", "gi": "70~80", "gl": "16", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "高GI精白米，控制总量。"},
    {"name": "长粒籼米", "category": "主食", "gi": "68~75", "gl": "16", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "升糖偏快，控制总量。"},
]

# ============================================================
# 关卡5：GL 专项卡牌库
# ============================================================
GL_FOODS = [
    # ---- 低GL（≤10）----
    {"name": "燕麦", "category": "主食", "gi": "55", "gl": "9", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，选原粒燕麦。"},
    {"name": "糙米", "category": "主食", "gi": "68", "gl": "10", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "低GL主食，优于白米饭。"},
    {"name": "全麦面包", "category": "主食", "gi": "55", "gl": "8", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "低GL，选真全麦，看配料表。"},
    {"name": "樱桃", "category": "水果", "gi": "22", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果，可适量吃。"},
    {"name": "草莓", "category": "水果", "gi": "27", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果，可适量吃。"},
    {"name": "柚子", "category": "水果", "gi": "24", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果，可适量吃。"},
    {"name": "南瓜", "category": "蔬菜", "gi": "75", "gl": "6", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "GI高但GL低，少量吃可。"},
    {"name": "甜菜根", "category": "蔬菜", "gi": "64", "gl": "5", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "胡萝卜", "category": "蔬菜", "gi": "71", "gl": "4", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "低GL，别大量吃。"},
    {"name": "绿叶菜", "category": "蔬菜", "gi": "15", "gl": "0", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，可放心多吃。"},
    {"name": "西兰花", "category": "蔬菜", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，可放心多吃。"},
    {"name": "黄瓜", "category": "蔬菜", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，可放心吃。"},
    {"name": "鸡蛋", "category": "蛋白", "gi": "0", "gl": "0", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "无碳水，低GL，优质蛋白。"},
    {"name": "鱼类", "category": "蛋白", "gi": "0", "gl": "0", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "无碳水，低GL，优质蛋白。"},
    {"name": "豆制品", "category": "蛋白", "gi": "0", "gl": "0", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，优质植物蛋白。"},
    {"name": "原味坚果", "category": "坚果", "gi": "20", "gl": "2~3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，但热量高，每天一小把。"},
    {"name": "无糖酸奶", "category": "饮品", "gi": "35", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，选无糖原味。"},
    {"name": "小番茄", "category": "水果", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，可适量吃。"},
    {"name": "李子", "category": "水果", "gi": "24", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "西梅", "category": "水果", "gi": "24", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "桃子", "category": "水果", "gi": "28", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "番石榴", "category": "水果", "gi": "31", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "木瓜", "category": "水果", "gi": "30", "gl": "2", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "梨子", "category": "水果", "gi": "36", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "橘子", "category": "水果", "gi": "43", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "苹果", "category": "水果", "gi": "36", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "橙子", "category": "水果", "gi": "43", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "蓝莓", "category": "水果", "gi": "34", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "火龙果", "category": "水果", "gi": "38", "gl": "4", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "鲜柿", "category": "水果", "gi": "50", "gl": "7", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，但含糖不低，控量。"},
    {"name": "牛油果", "category": "水果", "gi": "27", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，健康脂肪。"},
    {"name": "椰子肉", "category": "水果", "gi": "40", "gl": "3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL，含脂肪，适量。"},
    {"name": "猕猴桃", "category": "水果", "gi": "52", "gl": "6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "石榴", "category": "水果", "gi": "67", "gl": "9.4", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "菠萝", "category": "水果", "gi": "66", "gl": "7", "gi_level": "中GI", "gl_level": "低GL",
     "tip": "低GL水果。"},
    {"name": "西瓜", "category": "水果", "gi": "72", "gl": "4", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "陷阱！GI高但GL极低，少量吃负担小。"},
    {"name": "哈密瓜", "category": "水果", "gi": "70", "gl": "6", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "低GL，少量吃。"},
    {"name": "菠菜", "category": "蔬菜", "gi": "15", "gl": "1", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "生菜", "category": "蔬菜", "gi": "15", "gl": "0.3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "油菜", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "茼蒿", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "羽衣甘蓝", "category": "蔬菜", "gi": "15", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "冬瓜", "category": "蔬菜", "gi": "24", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "番茄", "category": "蔬菜", "gi": "15", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "西葫芦", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "香菇", "category": "蔬菜", "gi": "10", "gl": "0.3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL菌菇。"},
    {"name": "金针菇", "category": "蔬菜", "gi": "19", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL菌菇。"},
    {"name": "海带", "category": "蔬菜", "gi": "17", "gl": "0.3", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "鲜木耳", "category": "蔬菜", "gi": "26", "gl": "1.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL菌菇。"},
    {"name": "芦笋", "category": "蔬菜", "gi": "15", "gl": "0.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "秋葵", "category": "蔬菜", "gi": "20", "gl": "1.0", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "茄子", "category": "蔬菜", "gi": "15", "gl": "0.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL蔬菜。"},
    {"name": "生鹰嘴豆", "category": "蔬菜", "gi": "28", "gl": "5.6", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL豆类。"},
    {"name": "鲜豌豆", "category": "蔬菜", "gi": "54", "gl": "6.5", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL豆类，含碳水，适量。"},
    {"name": "山药", "category": "蔬菜", "gi": "75", "gl": "9.0", "gi_level": "高GI", "gl_level": "低GL",
     "tip": "GL低，但GI高，吃它减主食。"},
    {"name": "藜麦", "category": "主食", "gi": "53", "gl": "9", "gi_level": "低GI", "gl_level": "低GL",
     "tip": "低GL主食。"},
    # ---- 中GL（11-19）----
    {"name": "白米饭", "category": "主食", "gi": "70", "gl": "16", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "GI高+GL中，不是禁食，但要控量。"},
    {"name": "小米粥", "category": "主食", "gi": "70", "gl": "17", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "中GL，粥糊化升糖快，控量。"},
    {"name": "红薯", "category": "蔬菜", "gi": "70", "gl": "13", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "中GL，吃它减主食。"},
    {"name": "香蕉", "category": "水果", "gi": "60", "gl": "12", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "中GL，控制分量。"},
    {"name": "葡萄", "category": "水果", "gi": "56", "gl": "11", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "中GL，控制分量。"},
    {"name": "芒果", "category": "水果", "gi": "55", "gl": "10", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "中GL，控制分量。"},
    {"name": "饼干", "category": "零食", "gi": "60", "gl": "18~25", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "加工零食，GL高，少吃。"},
    {"name": "冬枣", "category": "水果", "gi": "42", "gl": "11", "gi_level": "低GI", "gl_level": "中GL",
     "tip": "陷阱！GI低但GL中，别大量吃。"},
    {"name": "榴莲", "category": "水果", "gi": "53", "gl": "15", "gi_level": "低GI", "gl_level": "中GL",
     "tip": "陷阱！碳水密度大，GL高，控量。"},
    {"name": "荔枝", "category": "水果", "gi": "70", "gl": "11", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "中GL，控量。"},
    {"name": "菠萝蜜", "category": "水果", "gi": "75", "gl": "19", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "中GL，控量。"},
    {"name": "土豆", "category": "蔬菜", "gi": "78~90", "gl": "15", "gi_level": "高GI", "gl_level": "中GL",
     "tip": "中GL，当主食吃。"},
    {"name": "红米饭", "category": "主食", "gi": "65", "gl": "14", "gi_level": "中GI", "gl_level": "中GL",
     "tip": "中GL主食，控量。"},
    {"name": "黑米饭", "category": "主食", "gi": "50", "gl": "11", "gi_level": "低GI", "gl_level": "中GL",
     "tip": "中GL主食，控量。"},
    # ---- 高GL（≥20）----
    {"name": "糯米", "category": "主食", "gi": "85~95", "gl": "28", "gi_level": "高GI", "gl_level": "高GL",
     "tip": "陷阱！高GI+高GL，严格少吃。"},
    {"name": "白面包", "category": "主食", "gi": "75", "gl": "25", "gi_level": "高GI", "gl_level": "高GL",
     "tip": "高GL，精制主食，少吃。"},
    {"name": "即食麦片", "category": "主食", "gi": "70", "gl": "22", "gi_level": "中GI", "gl_level": "高GL",
     "tip": "陷阱！加工即食，GL高，别当健康主食。"},
    {"name": "红枣", "category": "水果", "gi": "42", "gl": "29", "gi_level": "低GI", "gl_level": "高GL",
     "tip": "陷阱！GI不高但GL极高，极易升糖，严格少吃。"},
    {"name": "蛋糕", "category": "零食", "gi": "80", "gl": "20+", "gi_level": "高GI", "gl_level": "高GL",
     "tip": "高糖高脂高GL，严格少吃。"},
    {"name": "膨化食品", "category": "零食", "gi": "75", "gl": "22+", "gi_level": "高GI", "gl_level": "高GL",
     "tip": "高GL零食，严格少吃。"},
]

# ============================================================
# 关卡6：双维度毕业关卡（15 张陷阱卡）
# dual_class 取四分类：可少量吃 / 放心多吃 / 不能乱吃 / 严格少吃
# ============================================================
DUAL_CARDS = [
    {"name": "西瓜", "category": "水果", "gi": "72", "gl": "4",
     "gi_level": "高GI", "gl_level": "低GL", "dual_class": "可少量吃",
     "tip": "高GI+低GL：升糖快但负担小，少量吃没问题。"},
    {"name": "燕麦", "category": "主食", "gi": "55", "gl": "9",
     "gi_level": "低GI", "gl_level": "低GL", "dual_class": "放心多吃",
     "tip": "低GI+低GL：升糖慢负担小，放心吃。"},
    {"name": "糙米", "category": "主食", "gi": "68", "gl": "10",
     "gi_level": "低GI", "gl_level": "低GL", "dual_class": "放心多吃",
     "tip": "低GI+低GL：优质主食，放心吃。"},
    {"name": "黄瓜", "category": "蔬菜", "gi": "15", "gl": "1",
     "gi_level": "低GI", "gl_level": "低GL", "dual_class": "放心多吃",
     "tip": "低GI+低GL：放心多吃。"},
    {"name": "无糖酸奶", "category": "饮品", "gi": "35", "gl": "3",
     "gi_level": "低GI", "gl_level": "低GL", "dual_class": "放心多吃",
     "tip": "低GI+低GL：选无糖，放心吃。"},
    {"name": "红枣", "category": "水果", "gi": "42", "gl": "29",
     "gi_level": "低GI", "gl_level": "高GL", "dual_class": "不能乱吃",
     "tip": "陷阱！低GI但GL极高，碳水密度大，不能乱吃。"},
    {"name": "榴莲", "category": "水果", "gi": "53", "gl": "15",
     "gi_level": "低GI", "gl_level": "高GL", "dual_class": "不能乱吃",
     "tip": "陷阱！GI不高但GL高，严控分量。"},
    {"name": "荔枝", "category": "水果", "gi": "70", "gl": "11",
     "gi_level": "中GI", "gl_level": "高GL", "dual_class": "严格少吃",
     "tip": "升糖快+负担大，严格少吃。"},
    {"name": "糯米", "category": "主食", "gi": "85~95", "gl": "28",
     "gi_level": "高GI", "gl_level": "高GL", "dual_class": "严格少吃",
     "tip": "高GI+高GL：升糖快负担大，严格少吃。"},
    {"name": "红薯", "category": "蔬菜", "gi": "70", "gl": "13",
     "gi_level": "高GI", "gl_level": "中GL", "dual_class": "严格少吃",
     "tip": "GI高+GL不低，当主食并减量。"},
    {"name": "白米饭", "category": "主食", "gi": "70", "gl": "16",
     "gi_level": "高GI", "gl_level": "中GL", "dual_class": "严格少吃",
     "tip": "GI高+GL中，控量，非禁食。"},
    {"name": "即食麦片", "category": "主食", "gi": "70", "gl": "22",
     "gi_level": "中GI", "gl_level": "高GL", "dual_class": "严格少吃",
     "tip": "陷阱！加工即食，GL高，严格少吃。"},
    {"name": "芒果", "category": "水果", "gi": "55", "gl": "10",
     "gi_level": "中GI", "gl_level": "中GL", "dual_class": "严格少吃",
     "tip": "中GI+中GL，控制分量。"},
    {"name": "葡萄", "category": "水果", "gi": "56", "gl": "11",
     "gi_level": "中GI", "gl_level": "中GL", "dual_class": "严格少吃",
     "tip": "中GI+中GL，控制分量。"},
    {"name": "饼干", "category": "零食", "gi": "60", "gl": "18~25",
     "gi_level": "中GI", "gl_level": "高GL", "dual_class": "严格少吃",
     "tip": "加工零食，GL高，严格少吃。"},
]


# ============================================================
# 关卡定义
# ============================================================
# 类型 type：
#   "gi3"     三分类（低/中/高 GI）
#   "gl3"     三分类（低/中/高 GL）
#   "dual4"   四分类（速度×负担）
#   "quiz"    单选问答
LEVELS = [
    {
        "id": 0, "name": "场景一：认识GI/GL", "type": "intro",
        "content": [
            "小站（营养师）：老周，我们先来认识 GI，也就是升糖指数。",
            "GI 代表食物升高血糖的速度，很多糖友容易陷入误区，",
            "只凭印象判断 GI 高低，这就是『锚定效应』。",
            "",
            "【低GI】GI<55，血糖上升平缓",
            "【中GI】55≤GI≤70，血糖中等速度上升",
            "【高GI】GI>70，血糖快速飙升",
            "",
            "GL 血糖负荷 = GI × 碳水含量 ÷ 100，结合吃的份量，",
            "最贴近日常吃饭，评估一餐真实血糖压力。",
            "【低GL】GL<10  【中GL】10≤GL≤20  【高GL】GL>20",
            "",
            "一句话：GI 看升糖有多快，GL 看这一份给血糖多大压力。",
        ],
    },
    {
        "id": 1, "name": "关卡1：水果分类", "type": "gi3", "difficulty": "⭐",
        "pools": ["FRUITS"], "num_cards": 10, "pass_score": 8, "reward": 10,
        "objective": "破除『甜=高GI』的锚定误区",
        "dialogue": "第1关，水果卡牌分类！卡牌随机抽取。记住：水果甜≠高GI。放完全部卡牌后点【提交核对】，卡牌点击可看详情。",
        "review": {
            "低GI": "低GI水果升糖平缓，糖友可适量食用。",
            "中GI": "中GI水果要控制分量。",
            "高GI": "高GI水果升糖快，少量吃并关注GL。",
        },
    },
    {
        "id": 2, "name": "关卡2：蔬菜分类", "type": "gi3", "difficulty": "⭐⭐",
        "pools": ["VEGETABLES"], "num_cards": 10, "pass_score": 8, "reward": 10,
        "objective": "破除『所有蔬菜都低GI』的误区",
        "dialogue": "第2关，蔬菜卡牌！很多人认为所有蔬菜都能随便吃，这不对。土豆、红薯、南瓜等淀粉类蔬菜GI偏高，吃它们要减主食。",
        "review": {
            "低GI": "普通绿叶瓜茄类低GI，可多吃。",
            "中GI": "控制分量食用。",
            "高GI": "淀粉根茎类高GI，替代主食，不能额外吃。",
        },
    },
    {
        "id": 3, "name": "关卡3：主食分类", "type": "gi3", "difficulty": "⭐⭐⭐",
        "pools": ["STAPLES"], "num_cards": 8, "pass_score": 7, "reward": 10,
        "objective": "破除『主食都不能吃』的误区",
        "dialogue": "第3关，主食卡牌！主食不是洪水猛兽，用低/中GI杂粮替换高GI精白米饭。",
        "review": {
            "低GI": "黑米、藜麦、燕麦米是低GI好主食。",
            "中GI": "糙米、红米优于白米，控制总量。",
            "高GI": "糯米升糖极快，严格少吃。",
        },
    },
    {
        "id": 4, "name": "关卡4：GI混合闯关", "type": "gi3", "difficulty": "⭐⭐⭐⭐",
        "pools": ["FRUITS", "VEGETABLES", "STAPLES"], "num_cards": 12, "pass_score": 10, "reward": 10,
        "objective": "水果、蔬菜、主食全部打乱，独立判断GI",
        "dialogue": "终极挑战！卡牌不再分品类，全部打乱。独立判断每样食物的GI等级，仔细分辨陷阱食物！",
        "review": {
            "低GI": "低GI，升糖平缓。",
            "中GI": "中GI，控制分量。",
            "高GI": "高GI，升糖快，控量。",
        },
    },
    {
        "id": 5, "name": "关卡5：GL专项闯关", "type": "gl3", "difficulty": "⭐⭐⭐",
        "pools": ["GL_FOODS"], "num_cards": 12, "pass_score": 10, "reward": 10,
        "objective": "只判断GL血糖负荷等级",
        "dialogue": "恭喜完成GI训练！现在进入更贴合真实生活的GL训练。GI只看速度，GL才看你吃下去真实的血糖压力。按【低GL/中GL/高GL】分类。",
        "review": {
            "低GL": "低GL，血糖负担小，放心吃。",
            "中GL": "中GL，控制分量食用。",
            "高GL": "高GL，严格控制份量，尽量少吃。",
        },
    },
    {
        "id": 6, "name": "关卡6：GI+GL双维度毕业", "type": "dual4", "difficulty": "⭐⭐⭐⭐⭐",
        "pools": ["DUAL_CARDS"], "num_cards": 15, "pass_score": 12, "reward": 10,
        "objective": "速度+负担双重判断，矫正锚定效应",
        "dialogue": "最终结业考核！不能只看GI，也不能只看GL。独立判断每种食物的真实控糖属性，放入对应四档区间。",
        "review": {
            "可少量吃": "高GI+低GL：升糖快但负担小，少量吃。",
            "放心多吃": "低GI+低GL：升糖慢负担小，放心吃。",
            "不能乱吃": "低GI+高GL：碳水密度大，严控分量。",
            "严格少吃": "高/中GI+中/高GL：严格少吃。",
        },
    },
    {
        "id": 7, "name": "结业问答", "type": "quiz",
        "question": "下面哪一项说法是正确的？",
        "options": [
            "① 高GI食物绝对不能吃",
            "② 判断食物对血糖的影响，需要结合GI和食用份量（GL）综合判断",
            "③ 不甜的食物一定是低GI食物",
        ],
        "correct": 1,
        "explain": {
            "0": "不对！高GI食物不是完全不能吃，只要严格控制份量，GL不高就能少量品尝，例如西瓜少量吃。（-10分）",
            "1": "太棒了！GL兼顾升糖速度和食用份量，是糖友选食物更实用的工具。（+10分）",
            "2": "典型锚定误区！白米饭、土豆不甜但GI很高，不能靠甜度判断GI。（-10分）",
        },
    },
    {
        "id": 8, "name": "全局结算", "type": "result",
    },
]

# 总分阈值
RESULT_THRESHOLDS = [
    (40, "🎉优秀！熟练掌握各类食物GI分级，打破很多固有认知，学会GI+GL综合评估。"),
    (26, "👍良好，部分食物容易混淆，可以重玩终极混合关卡。"),
    (0,  "⚠️建议回看前置GI/GL知识点，针对性重玩薄弱关卡。"),
]

# 提示按钮消耗积分
HINT_COST = 10


def get_pool(name):
    """按字符串名取卡牌池。"""
    pools = {
        "FRUITS": FRUITS,
        "VEGETABLES": VEGETABLES,
        "STAPLES": STAPLES,
        "GL_FOODS": GL_FOODS,
        "DUAL_CARDS": DUAL_CARDS,
    }
    return pools[name]
